trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: MySecretsGroup   # Azure DevOps variable group name

steps:
- script: |
    echo "Accessing secret variable..."
    echo "The secret is: $(MY_SECRET)"
  displayName: "Read Secret Variable"
