trigger:
- main

pool:
  name: self-hosted-agent-pool   # your custom agent pool
  demands:
    - agent.name -equals windows-agent1  # force this specific agent

steps:
- script: echo "Hello from Azure DevOps + Bash 🚀"
  displayName: "Run Hello World Script"

- script: |
    bash week1-bash-basics/day1-basic-commands.sh
  displayName: "Run Day 1 Script"

