trigger:
- main

pool:
  name: self-hosted-agent-pool   # your custom agent pool
  demands:
    - agent.name -equals windows-agent1  # force this specific agent

steps:
- script: echo "Hello from Azure DevOps + Bash 🚀"
  displayName: "Run Hello World Script"

- script: |
    sudo apt-get update && sudo apt-get install -y dos2unix
    find . -type f -name "*.sh" -exec dos2unix {} \;
  displayName: "Normalize Line Endings (LF)"


- script: |
    bash week1-bash-basics/day1-basic-commands.sh
  displayName: "Run Day 1 Script"

